{% set name = "pyorbital" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5df148f4e4426c3bcbb6e800240df0725d18527cf97e1e34b06f06aea7347a0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - numpy >=1.6.0,!=1.14.0
  run:
    - python >=3.6
    - numpy >=1.6.0,!=1.14.0

test:
  imports:
    - pyorbital

about:
  home: https://github.com/pytroll/pyorbital
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Orbital parameters and astronomical computations in Python
  description: Orbital and astronomy computations in python
  doc_url: http://pyorbital.readthedocs.io
  dev_url: https://github.com/pytroll/pyorbital

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
