{% set name = "pyorbital" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc9e3ee973b312864ab16995c3fa290b004685f47808197bbd8c5f03851ae211

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy >=1.6.0,!=1.14.0
  run:
    - python
    - numpy >=1.6.0,!=1.14.0

test:
  imports:
    - pyorbital

about:
  home: https://github.com/pytroll/pyorbital
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Orbital parameters and astronomical computations in Python
  description: Orbital and astronomy computations in python
  doc_url: http://pyorbital.readthedocs.io
  dev_url: https://github.com/pytroll/pyorbital

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
