{% set name = "pyorbital" %}
{% set version = "1.5.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "8e963c117b661f6ab31d01bf6ed65ddb0da16d367bf277edb773a78dfadf56e1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy >=1.6.0,!=1.14.0
  run:
    - python
    - numpy >=1.6.0,!=1.14.0

test:
  imports:
    - pyorbital

about:
  home: https://github.com/pytroll/pyorbital
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Orbital parameters and astronomical computations in Python
  description: Orbital and astronomy computations in python
  doc_url: http://pyorbital.readthedocs.io
  dev_url: https://github.com/pytroll/pyorbital

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
