{% set name = "pyorbital" %}
{% set version = "1.12.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f8c432bf06f195aca8ef2a216f3bf5bb31896b39bb54649db0cf4fbe4880b2fa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
    - numpy >=1.19.0
  run:
    - python >={{ python_min }}
    - numpy >=1.19.0
    - scipy
    - defusedxml
    - requests
    - pyproj
    - donfig

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyorbital

about:
  home: https://github.com/pytroll/pyorbital
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Orbital parameters and astronomical computations in Python
  description: Orbital and astronomy computations in python
  doc_url: http://pyorbital.readthedocs.io
  dev_url: https://github.com/pytroll/pyorbital

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
