travis:
  secure:
    BINSTAR_TOKEN: LUnqF66028sv9qsW5Ta5rWH4k9LpCb0jq7BNcA/lg8hSrN592vXYg5NjcVqu36YU2YaJbiRgPMqi/oZNur31Yj1Eicwewktg7aCvWf5EFxwaG03M+8ecXi2bjierSZKXDeGrL8LE5tlJCAxd7r3qFPgVlrfKxxLoS8zKqfPJnhg3tH+y5Nq39YwNX9yJnAZnFBFGyllfXNTXvbs+LJ+rhwvgM9tXNayqrarIMHnr3L/8Cb2EQzfyjp5HDmap9ycr2iyNhNG3I5bj3UWAJkAu531YisZoVHNgqWNZzUktxVNtYaJOt1YImRqJHRtFB5ZxPjGMfbGnZoN6tOAKU0N4nsjOOc3obtu80zRj8AnfM+glJmb52nI1lVki9r06V5byDyQgZXac42BI6vACpuC6MDbPX2iIdTpYsu8OTM0gHqEvVKULWOjMUvU8YQ6Xt70qZ9Cq/YskjlCPEBFZOqJz5LPoTdN+QbWwEsVDyQwhwct1BlPbT06llgZkUwkYxLfqFZt9ugdoCa3GKcQEENz4aUUs8MhUVSVq82edkzZyfyegELJmTM5KSjf+3tpWlPStv/7pFWoYECQTSem8W+fLsYS/OvgbLJXFMfg5DWjQNPSdOlxJJZf5ttLQzs9z8Vfn+TW52Bqyar/xgqfpc3e/aYFfAnzL6e9jm3jk75hxgkw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
