travis:
  secure:
    BINSTAR_TOKEN: QpdfVeXzmSQIiIiYGt3kRfuqAtivU9XZa14ZkPd2w5ojG35ZU+yrzHFtiA836S+fk5KZ8yskBTnVPYGN+DDzff3FzBsWtoBppMVQueL3m2ZYOK5BtkuMBvN/gOKHM2kNlhkAuvPmpFqnfvr77gCJtzwF1TN0fd025e8IYExi4liNTBLjU3Vrjxi8km2WfJEqtthHIca6Iy830L+p70152y8zSH3GJvrSLpXHDJ3kWO4DNFAavtOp+BR3Emzdo0XhP/Wpo4sayAjFI8OQ3iy0SU+xXfoZBDKxAWSkcgY1ldgmi+6TDDDlh0gs3baJ2NEOaIu9A/G5o0J4suCKOnzKjGsrXRtHcXJ+j8muZlmjfZkNPsn7ERLrCp0LD2Ir9cAMgp9HHnDEXi1C9wz2ZKY+fRl3oP+eiYOtCw25cz+y15RtAsjMPjaD7hCrx4aSdGflXoggreB2wpdEB0EzQBeRWCpVFfzSQMKSRLYRS/98rXe6eDuU3TJ6sRXPePxR2k4CHQfU34Krd9GkNM9IYoZ2WReGzU/tavC19FqAmiKK+DRPIfcpjMLpgCVV78d0jowYRsRNTzvlncLdPGh2V5VEy2WH6BbzJ2FXkRyiwAcMC1Taxtji81xT4wcB+zYBEPZCi1G6IEDfKI2a2FU5p45w1hyDzqtv6WDfCGhJnWgCCAI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
